id: ID2C7C917
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:18:29.799492+00:00
last_modified: 2022-12-15 07:18:29.799498+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: tei
  datatype: Text
  eft-text-id: UT22084-044-006
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_86-The_Question_of_Maitreya_on_the_Eight_Qualities-v1
bases:
  779F:
    source_metadata: null
    order: 1
    base_file: 779F.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
